Repository VNG-Realisatie/api-beheer, pull requests merged in 2019-07, with the labels that each got.

#149 Update RM-API-Beheer.md
  Processen/RM-API-Beheer.md
Labels: Beheerder, Gemeenten, Leverancier, Prio H

#151 Update CR-PR-ATV.md
  Processen/CR-PR-ATV.md
Labels: Beheerder, Beheeromgeving, Gemeenten, Leverancier, Prio H

#146 Update Beheerlandschap.md
  Beheerlandschap.md
Labels: Beheerder, Beheeromgeving, Documentatie, Prio H

#152 Update RM-ATV.md
  Processen/RM-ATP.md
  Processen/RM-ATV.md
Labels: Beheerder, Beheeromgeving, Gemeenten, Leverancier, prio M

#154 Update checklist_inbeheer_nemen.md
  checklist_inbeheer_nemen.md
Labels: Beheerder
